name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create docs directory and HTML
      run: |
        mkdir -p docs
        cat > docs/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="pt-BR">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Exercício Módulo 22 - Relatório</title>
            <style>
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    margin: 0;
                    padding: 20px;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    min-height: 100vh;
                }
                .container {
                    max-width: 900px;
                    margin: 0 auto;
                    background: white;
                    padding: 40px;
                    border-radius: 15px;
                    box-shadow: 0 15px 35px rgba(0,0,0,0.3);
                }
                h1 {
                    color: #2c3e50;
                    text-align: center;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 20px;
                    margin-bottom: 30px;
                }
                .status {
                    background: linear-gradient(45deg, #27ae60, #2ecc71);
                    color: white;
                    padding: 20px;
                    border-radius: 10px;
                    text-align: center;
                    font-weight: bold;
                    margin: 25px 0;
                    font-size: 18px;
                }
                .info-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                    gap: 20px;
                    margin: 30px 0;
                }
                .info-box {
                    background: #f8f9fa;
                    padding: 25px;
                    border-radius: 10px;
                    border-left: 5px solid #3498db;
                }
                .info-box h3 {
                    color: #2c3e50;
                    margin-top: 0;
                }
                .footer {
                    text-align: center;
                    color: #7f8c8d;
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 2px solid #bdc3c7;
                }
                a {
                    color: #3498db;
                    text-decoration: none;
                }
                a:hover {
                    text-decoration: underline;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🎉 Exercício Módulo 22 - GitHub Pages Funcionando!</h1>
                
                <div class="status">
                    ✅ Site publicado com sucesso via GitHub Actions!
                </div>
                
                <div class="info-grid">
                    <div class="info-box">
                        <h3>📊 Informações do Deploy</h3>
                        <p><strong>Repository:</strong> exerc-cio-modulo-22</p>
                        <p><strong>Branch:</strong> ${{ github.ref_name }}</p>
                        <p><strong>Commit:</strong> ${{ github.sha }}</p>
                        <p><strong>Author:</strong> ${{ github.actor }}</p>
                        <p><strong>Workflow:</strong> ${{ github.workflow }}</p>
                    </div>
                    
                    <div class="info-box">
                        <h3>🧪 Status dos Testes</h3>
                        <p>✅ GitHub Actions configurada</p>
                        <p>✅ GitHub Pages ativo</p>
                        <p>✅ Deploy automático funcionando</p>
                        <p>✅ Site HTML gerado dinamicamente</p>
                    </div>
                </div>
                
                <div class="info-box">
                    <h3>🔗 Links Úteis</h3>
                    <p>📂 <a href="https://github.com/${{ github.repository }}" target="_blank">Ver Repositório no GitHub</a></p>
                    <p>⚡ <a href="https://github.com/${{ github.repository }}/actions" target="_blank">Ver GitHub Actions</a></p>
                    <p>🔧 <a href="https://github.com/${{ github.repository }}/settings/pages" target="_blank">Configurações do Pages</a></p>
                </div>
                
                <div class="footer">
                    <h4>🤖 Gerado Automaticamente</h4>
                    <p>Este relatório foi criado automaticamente pela GitHub Action</p>
                    <p><strong>Exercício:</strong> Módulos 22-25 - GitHub Actions + GitHub Pages</p>
                    <p><strong>Data de criação:</strong> <script>document.write(new Date().toLocaleString('pt-BR'))</script></p>
                </div>
            </div>
        </body>
        </html>
        EOF
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
